### ISSUE TITLE
Raspberry pi4 w/4g installation errors

### ISSUE THREAD

**Issue by osilloh** [btcpayserver/btcpayserver#1009]
**Describe the problem/bug**
This could be user error and not a bug. 

**Your environment**
* Version of BTCPay Server: btcpayserver:1.0.3.127
* Deployment method: RaspberryPi4, 4g.
* Other relevant environment details:

I am using DNS. Should I use raspberrypi.local from what I've read, it should work without DNS since it uses TOR, yes?

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**

**Expected behavior**

btcpayserver_bitcoind is failing to synchronize

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs --tail 10 btcpayserver_bitcoind
2019-09-04T01:13:54Z UpdateTip: new best=000000000000000000079706d09006afe381ddc4e483550318f398cbe28c7f6e height=593148 version=0x3fffe000 log2_work=91.041492 tx=451663534 date='2019-09-04T01:14:09Z' progress=1.000000 cache=70.4MiB(623545txo) warning='46 of last 100 blocks have unexpected version'
2019-09-04T01:35:02Z UpdateTip: new best=00000000000000000007b4d0d5d48eb2f61a0c50e1687d5a635d26f7081f6b8f height=593149 version=0x20000000 log2_work=91.041518 tx=451666231 date='2019-09-04T01:33:25Z' progress=0.999999 cache=71.1MiB(630312txo) warning='46 of last 100 blocks have unexpected version'
2019-09-04T01:46:53Z ping timeout: 1200.004103s
2019-09-04T01:47:01Z New outbound peer connected: version: 70015, blocks=593149, peer=2415
2019-09-04T01:47:13Z UpdateTip: new best=0000000000000000000f2979536394d8c7358f7f9b4110ec8e79a16434f13e72 height=593150 version=0x20000000 log2_work=91.041545 tx=451669194 date='2019-09-04T01:46:35Z' progress=1.000000 cache=71.5MiB(633802txo) warning='45 of last 100 blocks have unexpected version'
2019-09-04T01:58:47Z Pre-allocating up to position 0x600000 in rev01781.dat
2019-09-04T01:58:47Z UpdateTip: new best=000000000000000000056b823b3520e37db82550d510abedf11f36302a950bf3 height=593151 version=0x20000000 log2_work=91.041571 tx=451672286 date='2019-09-04T01:58:21Z' progress=1.000000 cache=71.8MiB(636891txo) warning='44 of last 100 blocks have unexpected version'
2019-09-04T02:06:23Z UpdateTip: new best=00000000000000000016b287121883052ce18e98ea03079b75ae5c3b716ba432 height=593152 version=0x20000000 log2_work=91.041597 tx=451675191 date='2019-09-04T02:05:56Z' progress=1.000000 cache=72.2MiB(640185txo) warning='43 of last 100 blocks have unexpected version'
2019-09-04T02:22:22Z UpdateTip: new best=00000000000000000019810c8a743b555a3730a6b0acd045702bce00c6d23e2c height=593153 version=0x20400000 log2_work=91.041623 tx=451677216 date='2019-09-04T02:21:47Z' progress=1.000000 cache=73.8MiB(654973txo) warning='44 of last 100 blocks have unexpected version'
2019-09-04T02:32:24Z UpdateTip: new best=000000000000000000189d7bc4661db1bcb767ff3402e8d25c9a46f53589fe89 height=593154 version=0x20400000 log2_work=91.041649 tx=451679121 date='2019-09-04T02:32:01Z' progress=1.000000 cache=6.4MiB(27700txo) warning='45 of last 100 blocks have unexpected version'
root@raspberrypi:~/btcpayserver/btcpayserver-docker# 

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs --tail 10 tor
Sep 02 22:34:04.000 [notice] Heartbeat: Tor's uptime is 2 days 0:00 hours, with 45 circuits open. I've sent 45.27 MB and received 84.39 MB.
Sep 02 22:34:04.000 [notice] Our onion services received 0 v2 and 0 v3 INTRODUCE2 cells and attempted to launch 0 rendezvous circuits.
Sep 03 04:34:05.000 [notice] Heartbeat: Tor's uptime is 2 days 6:00 hours, with 21 circuits open. I've sent 51.03 MB and received 88.12 MB.
Sep 03 04:34:05.000 [notice] Our onion services received 0 v2 and 0 v3 INTRODUCE2 cells and attempted to launch 0 rendezvous circuits.
Sep 03 10:34:04.000 [notice] Heartbeat: Tor's uptime is 2 days 12:00 hours, with 35 circuits open. I've sent 59.03 MB and received 130.15 MB.
Sep 03 10:34:04.000 [notice] Our onion services received 0 v2 and 1 v3 INTRODUCE2 cells and attempted to launch 1 rendezvous circuits.
Sep 03 16:34:04.000 [notice] Heartbeat: Tor's uptime is 2 days 18:00 hours, with 31 circuits open. I've sent 77.22 MB and received 339.04 MB.
Sep 03 16:34:04.000 [notice] Our onion services received 0 v2 and 1 v3 INTRODUCE2 cells and attempted to launch 1 rendezvous circuits.
Sep 03 22:34:04.000 [notice] Heartbeat: Tor's uptime is 3 days 0:00 hours, with 47 circuits open. I've sent 94.83 MB and received 507.43 MB.
Sep 03 22:34:04.000 [notice] Our onion services received 0 v2 and 1 v3 INTRODUCE2 cells and attempted to launch 1 rendezvous circuits.
root@raspberrypi:~/btcpayserver/btcpayserver-docker# 

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs --tail 10 generated_btcpayserver_1
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at BTCPayServer.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /source/BTCPayServer/MigrationStartupTask.cs:line 91
   at BTCPayServer.MigrationStartupTask.ExecuteAsync(CancellationToken cancellationToken) in /source/BTCPayServer/MigrationStartupTask.cs:line 37
   at BTCPayServer.Extensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken) in /source/BTCPayServer/Extensions.cs:line 60
   at BTCPayServer.Program.Main(String[] args) in /source/BTCPayServer/Program.cs:line 72

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker stats

CONTAINER ID        NAME                                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
f837f1ba1558        letsencrypt-nginx-proxy-companion   0.42%               11.69MiB / 3.814GiB   0.30%               63.2MB / 870B       444MB / 4.1kB       16
ccfab82ea078        nginx-gen                           0.27%               7.508MiB / 3.814GiB   0.19%               63.2MB / 690B       3.83MB / 20.2MB     17
b2c8590145b8        nginx                               0.00%               3.125MiB / 3.814GiB   0.08%               65.4MB / 3.37MB     4.87MB / 0B         2
d2780866cae0        btcpayserver_lnd_bitcoin            2.61%               740.7MiB / 3.814GiB   18.96%              15GB / 786MB        30.8MB / 1.35GB     19
ed845bd85c81        btcpayserver_bitcoind               21.46%              327.8MiB / 3.814GiB   8.39%               11.8GB / 15.4GB     146GB / 152GB       18
bfdfecca332f        tor-gen                             0.28%               6.938MiB / 3.814GiB   0.18%               63.2MB / 870B       11.1MB / 12.3kB     16
30db4757df75        generated_lnd_bitcoin_rtl_1         0.00%               2.387MiB / 3.814GiB   0.06%               63.2MB / 870B       35.6MB / 0B         12
8cef15e653f3        tor                                 0.31%               14.55MiB / 3.814GiB   0.37%               752MB / 671MB       110MB / 125MB       1
26ec2853b513        generated_nbxplorer_1               2.53%               147.8MiB / 3.814GiB   3.78%               756MB / 57.5MB      160MB / 219MB       24
7de6a1325996        generated_btcpayserver_1            1.19%               3.043MiB / 3.814GiB   0.08%               12kB / 2.13kB       9.04MB / 17.9MB     1
**Actual behavior**
It has been stuck like this for over 24 hrs.

**Screenshots/Links**
Hope the above helps, not sure which output I should post.

**Additional context**
I did the optional Fastsync method.

**Comment by NicolasDorier** [comment]
ok so several possible cause:

Do you have enough space? (check with `df -h`)

Try also `btcpay-up.sh` maybe it will solve the problem.

**Comment by osilloh** [comment]
I believe I did the opt-save-storage.

root@raspberrypi:~/btcpayserver/btcpayserver-docker# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G  5.6G   23G  20% /
devtmpfs        1.8G     0  1.8G   0% /dev
tmpfs           2.0G   12M  1.9G   1% /dev/shm
tmpfs           2.0G  210M  1.8G  11% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   41M  213M  16% /boot
/dev/sda1       117G   17G   95G  15% /mnt/usb

running btcpay-up.sh now

thank you.

**Comment by osilloh** [comment]
root@raspberrypi:~/btcpayserver/btcpayserver-docker# btcpay-up.sh
generated_nbxplorer_1 is up-to-date
generated_lnd_bitcoin_rtl_1 is up-to-date
tor is up-to-date
generated_postgres_1 is up-to-date
tor-gen is up-to-date
btcpayserver_bitcoind is up-to-date
btcpayserver_lnd_bitcoin is up-to-date
generated_btcpayserver_1 is up-to-date
nginx is up-to-date
nginx-gen is up-to-date
letsencrypt-nginx-proxy-companion is up-to-date
root@raspberrypi:~/btcpayserver/btcpayserver-docker#

**Comment by osilloh** [comment]
Any other suggestions would be greatly appreciated. If I have to start over, that is also fine. It is a good learning experience for me :)

**Comment by NicolasDorier** [comment]
still same errors in the log?

**Comment by NicolasDorier** [comment]
can you check the logs of `docker logs generated_postgres_1`

**Comment by osilloh** [comment]
the btcpayserver_bitcoind still has the same errors.

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs --tail 10 btcpayserver_bitcoind
2019-09-05T07:35:10Z UpdateTip: new best=0000000000000000000d7122c385697a5280faaa9a9936fba95473b725dd4459 height=593327 version=0x2e47a000 log2_work=91.046173 tx=452077400 date='2019-09-05T07:34:39Z' progress=1.000000 cache=62.9MiB(555536txo) warning='47 of last 100 blocks have unexpected version'

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs generated_postgres_1

postgres: could not find the database system
Expected to find it in the directory "/var/lib/postgresql/data",
but could not open file "/var/lib/postgresql/data/global/pg_control": No such file or directory
postgres: could not find the database system
Expected to find it in the directory "/var/lib/postgresql/data",
but could not open file "/var/lib/postgresql/data/global/pg_control": No such file or directory
postgres: could not find the database system
Expected to find it in the directory "/var/lib/postgresql/data",
but could not open file "/var/lib/postgresql/data/global/pg_control": No such file or directory
root@raspberrypi:~/btcpayserver/btcpayserver-docker#

**Comment by NicolasDorier** [comment]
@osilloh wow this is a curious error, first time I see that on postgres. You have nothing important? we can just delete postgres data.

**Comment by NicolasDorier** [comment]
If you can delete postgres:

```
btcpay-down.sh
rm -rf /var/lib/docker/volumes/generated_postgres_datadir/_data
mkdir -p /var/lib/docker/volumes/generated_postgres_datadir/_data
btcpay-up.sh
```

**Comment by osilloh** [comment]
Thank you again for your assistance!

The above commands completed, with output below:

root@raspberrypi:~/btcpayserver/btcpayserver-docker# btcpay-down.sh
Stopping letsencrypt-nginx-proxy-companion ... done
Stopping nginx-gen                         ... done
Stopping generated_btcpayserver_1          ... done
Stopping nginx                             ... done
Stopping btcpayserver_lnd_bitcoin          ... done
Stopping btcpayserver_bitcoind             ... done
Stopping tor-gen                           ... done
Stopping generated_postgres_1              ... done
Stopping generated_lnd_bitcoin_rtl_1       ... done
Stopping tor                               ... done
Stopping generated_nbxplorer_1             ... done
Removing letsencrypt-nginx-proxy-companion ... done
Removing nginx-gen                         ... done
Removing generated_btcpayserver_1          ... done
Removing nginx                             ... done
Removing btcpayserver_lnd_bitcoin          ... done
Removing btcpayserver_bitcoind             ... done
Removing tor-gen                           ... done
Removing generated_postgres_1              ... done
Removing generated_lnd_bitcoin_rtl_1       ... done
Removing tor                               ... done
Removing generated_nbxplorer_1             ... done
Removing network generated_default
root@raspberrypi:~/btcpayserver/btcpayserver-docker# 

root@raspberrypi:~/btcpayserver/btcpayserver-docker# rm -rf /var/lib/docker/volumes/generated_postgres_datadir/_data

root@raspberrypi:~/btcpayserver/btcpayserver-docker# mkdir -p /var/lib/docker/volumes/generated_postgres_datadir/_data


root@raspberrypi:~/btcpayserver/btcpayserver-docker# btcpay-up.sh
Creating network "generated_default" with the default driver
Creating tor                         ... done
Creating generated_nbxplorer_1       ... done
Creating generated_lnd_bitcoin_rtl_1 ... done
Creating generated_postgres_1        ... done
Creating btcpayserver_bitcoind       ... done
Creating tor-gen                     ... done
Creating btcpayserver_lnd_bitcoin    ... done
Creating generated_btcpayserver_1    ... done
Creating nginx                       ... done
Creating nginx-gen                   ... done
Creating letsencrypt-nginx-proxy-companion ... done
root@raspberrypi:~/btcpayserver/btcpayserver-docker# 



root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs generated_postgres_1
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
****************************************************
WARNING: No password has been set for the database.
         This will allow anyone with access to the
         Postgres port to access your database. In
         Docker's default configuration, this is
         effectively any other container on the same
         system.

         Use "-e POSTGRES_PASSWORD=password" to set
         it in "docker run".
****************************************************
waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  database system was shut down at 2019-09-05 17:02:16 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
ALTER ROLE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

LOG:  received fast shutdown request
LOG:  aborting any active transactions
waiting for server to shut down....LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2019-09-05 17:02:48 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  database "btcpayservermainnet" does not exist
FATAL:  database "btcpayservermainnet" does not exist
LOG:  using stale statistics instead of current ones because stats collector is not responding
LOG:  using stale statistics instead of current ones because stats collector is not responding
root@raspberrypi:~/btcpayserver/btcpayserver-docker#

**Comment by NicolasDorier** [comment]
seems good, btcpay should work now. Else, give the logs of btcpay

**Comment by osilloh** [comment]
the bitcoind process appears to still not be sync'd. Is this ok?

Do I need to execute these commands? I tried and I must be entering them incorrectly. I am trying to read up on docker containers, really cool tech, but a few hours has not made me proficient yet heheh.

pg_ctl -D /var/lib/postgresql/data -l logfile start

Use "-e POSTGRES_PASSWORD=password" to set
     it in "docker run".

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs --tail 10 btcpayserver_bitcoind
2019-09-06T06:13:53Z UpdateTip: new best=000000000000000000163f6060d8623196bdf51e4369715f1588e3f3dddee801 height=593486 version=0x20000000 log2_work=91.050319 tx=452418208 date='2019-09-06T06:13:44Z' progress=1.000000 cache=48.1MiB(433488txo) warning='42 of last 100 blocks have unexpected version'
2019-09-06T06:16:43Z UpdateTip: new best=00000000000000000016d3e7f37b16c3e7afc32800f33732aba20e6bf6d45824 height=593487 version=0x20400000 log2_work=91.050345 tx=452419014 date='2019-09-06T06:16:22Z' progress=1.000000 cache=48.2MiB(434514txo) warning='43 of last 100 blocks have unexpected version'
2019-09-06T06:23:23Z Leaving block file 1783: CBlockFileInfo(blocks=130, size=133518939, heights=593358...593487, time=2019-09-05...2019-09-06)
2019-09-06T06:23:24Z Pre-allocating up to position 0x1000000 in blk01784.dat
2019-09-06T06:23:24Z Pre-allocating up to position 0x100000 in rev01784.dat
2019-09-06T06:23:24Z UpdateTip: new best=000000000000000000062e18444c596de64b68ffd23477e84a3e09e057475963 height=593488 version=0x20000000 log2_work=91.050371 tx=452421042 date='2019-09-06T06:23:06Z' progress=1.000000 cache=48.4MiB(436585txo) warning='42 of last 100 blocks have unexpected version'
2019-09-06T06:24:01Z UpdateTip: new best=00000000000000000010e31facf432faf3e9e245c944a7d4a1b4b4f0c23ea90c height=593489 version=0x2000e000 log2_work=91.050397 tx=452421214 date='2019-09-06T06:23:40Z' progress=1.000000 cache=48.4MiB(436437txo) warning='43 of last 100 blocks have unexpected version'
2019-09-06T06:33:44Z UpdateTip: new best=0000000000000000000d43ec966912cc48462688bd916e26b68a8e590af95f66 height=593490 version=0x3fff0000 log2_work=91.050423 tx=452424024 date='2019-09-06T06:33:59Z' progress=1.000000 cache=48.9MiB(440611txo) warning='44 of last 100 blocks have unexpected version'
2019-09-06T06:39:18Z UpdateTip: new best=00000000000000000009c5bbe42500903b4ad400d230f2fe7abbb42a4e3c27bd height=593491 version=0x20400000 log2_work=91.050449 tx=452426126 date='2019-09-06T06:38:44Z' progress=1.000000 cache=49.1MiB(442809txo) warning='44 of last 100 blocks have unexpected version'
2019-09-06T06:44:15Z UpdateTip: new best=0000000000000000000507faf2ce7398e726af89f1b5ff77fde6ec59b2069482 height=593492 version=0x20c00000 log2_work=91.050475 tx=452427912 date='2019-09-06T06:44:07Z' progress=1.000000 cache=51.1MiB(445072txo) warning='44 of last 100 blocks have unexpected version'
root@raspberrypi:~/btcpayserver/btcpayserver-docker#

**Comment by osilloh** [comment]
hmmm, not sure if BTCpay is working.

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs --tail 10 generated_btcpayserver_1
info: PayServer:      User logged in.
info: Events:         BTC: New block
info: Events:         BTC: New block
info: Events:         BTC: New block
info: Events:         BTC: New block
info: Events:         BTC: New block
info: Events:         BTC: New block
info: Events:         BTC: New block
info: Events:         BTC: New block
info: Events:         BTC: New block
root@raspberrypi:~/btcpayserver/btcpayserver-docker# 

but as I posted above bitcoind not syncing and below, lnd errors

root@raspberrypi:~/btcpayserver/btcpayserver-docker# docker logs --tail 10 btcpayserver_lnd_bitcoin

2019-09-06 07:17:24.691 [ERR] CMGR: Can't accept connection: unable to accept connection from 18.188.244.93:34374: chacha20poly1305: message authentication failed
2019-09-06 07:17:45.134 [INF] CRTR: Processed channels=0 updates=4 nodes=0 in last 59.999935767s
2019-09-06 07:18:45.098 [INF] DISC: Broadcasting 4 new announcements in 1 sub batches
2019-09-06 07:18:45.134 [INF] CRTR: Processed channels=0 updates=2 nodes=0 in last 59.999693843s
2019-09-06 07:19:45.133 [INF] CRTR: Processed channels=0 updates=6 nodes=0 in last 59.999507337s
2019-09-06 07:20:15.097 [INF] DISC: Broadcasting 10 new announcements in 1 sub batches
2019-09-06 07:20:45.134 [INF] CRTR: Processed channels=0 updates=4 nodes=1 in last 59.999748113s
2019-09-06 07:21:07.309 [ERR] CMGR: Can't accept connection: unable to accept connection from 18.188.244.93:34368: chacha20poly1305: message authentication failed
2019-09-06 07:21:08.192 [ERR] CMGR: Can't accept connection: unable to accept connection from 18.188.244.93:34369: chacha20poly1305: message authentication failed
2019-09-06 07:21:26.889 [ERR] CMGR: Can't accept connection: unable to accept connection from 18.188.244.93:34370: chacha20poly1305: message authentication failed
root@raspberrypi:~/btcpayserver/btcpayserver-docker#

**Comment by pavlenex** [comment]
Maybe @wiz has some ideas on the RPI4.

**Comment by wiz** [comment]
The error messages feel like hardware issues to me. Few questions:

1. What power supply are you using?
2. What SD card are you using?
3. What cooling are you using?
4. Do you see any errors in output of `dmesg` ?

**Comment by NicolasDorier** [comment]
Closing for no activity
