### ISSUE TITLE
Wasabi BTCPayServer connection 

### ISSUE THREAD

**Issue by bjadel** [btcpayserver/btcpayserver#1221]
Hi,

I have installed the BTCPayServer on a RaspiBlitz. My problem is the configuration of the Wasabi Wallet. I see incoming Bitcoin payments in the BTCPay interface but not in Wasabi. Maybe I just have an understanding problem. During the configuration of the Wasabi Wallet the addresses were identical (https://docs.btcpayserver.org/getting-started/connectwallet/wasabiwallet) and I confirmed this with 'Confirm'. Then a Bitcoin payment came in and I also saw it in the BTCPay interface.  In Wasabi there was nothing to see. Then I generated a new address in Wasabi in the tab Receive and when I looked at it in the Block Explorer, there was also the transaction available. But in Wasabi itself I still don't see anything of this transaction or the bitcoins. I thought the Wasabi Wallet is a mirror image of the wallet in the BTCPay server.

I would be very grateful for help.

Many greetings
Björn

**Comment by pavlenex** [comment]
Hi Bjorn, this is "normal" occurrence on an external wallets, called [the gap limit](https://github.com/btcpayserver/btcpayserver-doc/blob/master/FAQ/FAQ-Wallet.md#missing-payments-in-my-software-or-hardware-wallet)

Luckily since you're using Wasabi, you should be able to [change the default gap limit as described in our official documentation.](https://docs.btcpayserver.org/getting-started/connectwallet/wasabiwallet#configuring-the-gap-limit-in-wasabi)

**Comment by bjadel** [comment]
I had already set the gab limit to 100. Is this really the problem? After all, I have only one transaction (confirmed) and it is not visible. I also wonder how Wasabi finds the new Receive addresses? And how do I proceed in Wasabi? Do I always have to create the Receive addresses manually or shouldn't Wasabi recognize them on a automatic way? Questions about questions :-) But one thing I have to say, the BTCPay server is really cool.

**Comment by pavlenex** [comment]
I'm not familiar with how Wasabi works, but as long as the wallets have the same xpubkey and a proper format set, you are good. If the transaction is not visible in external wallet it's the gap limit issue and you should increase the gap limit. You may want to ask Wasabi developers if the gap limit really works.

I remember @NicolasDorier had some opinion on it, but can't remember if it was fixed. Maybe @nopara73 can help us out on this one.

**Comment by nopara73** [comment]
Was Wasabi open the time you received the payment? If no, then you won't see it until it confirms.

**Comment by bjadel** [comment]
> Was Wasabi open the time you received the payment? If no, then you won't see it until it confirms.

Yes, Wasabi was open and the transaction was confirmed. The history is empty.

**Comment by nopara73** [comment]
I have not heard of Wasabi not showing up money received from outside, so sorry if I rehash something that has been explored previously before, but I think it must be something simple.

- First of all, today there'll be a Wasabi release with a bunch of refactoring on wallet internals, so could you try that before going forward?
- Is it a p2wpkh address?
- Can you see the tx in a block explorer?
- Can you see the block it confirmed in in your Blocks folder? (in the wasabi work dir)
- Can you figure out what is the index of your address? And what happens if you elevate the gap limit (in the wallet file)?

**Comment by bjadel** [comment]
> I have not heard of Wasabi not showing up money received from outside, so sorry if I rehash something that has been explored before, but I think it must be something simple.
> 
>     * First of all, today there'll be a Wasabi release with a bunch of refactoring on wallet internals, so could you try that before going forward?
> 
>     * Is it a p2wpkh address?
> 
>     * Can you see the tx in a block explorer?
> 
>     * Can you see the block it confirmed in in your Blocks folder? (in the wasabi work dir)
> 
>     * Can you figure out what is the index of your address? And what happens if you elevate the gap limit (in the wallet file)?

Thanks for the answer. I will answer the questions in the next few days.

**Comment by NicolasDorier** [comment]
> But in Wasabi itself I still don't see anything of this transaction or the bitcoins. I thought the Wasabi Wallet is a mirror image of the wallet in the BTCPay server.

It happened to me as well. Normally wasabi should have some sort of huge gap limit, but unsure that it work properly.

**Comment by nopara73** [comment]
There was a bug that may be related (fix is released in 1.1.10.1) https://github.com/zkSNACKs/WalletWasabi/issues/2859

Wasabi previously did not look at the gap, rather the it looked at the total number of clean keys instead.

**Comment by NicolasDorier** [comment]
It is possible that this is fixed by now. I created my wallet before that.

**Comment by bjadel** [comment]
I have now opened my wallet with Wasabi version 1.1.10.1. The problem still existed. In the meantime I tried to use Electrum. With this it works without problems.

**Comment by NicolasDorier** [comment]
@bjadel you need to delete and restore your wallet with wasabi. It does not solve by itself without rescanning on wasabi.

Closing this, as this should be fixed on wasabi side. (I could confirm with my own wallet)
