### ISSUE TITLE
The type or namespace name 'LightningNetworkPaymentMethodData' could not be found dev enviroment

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2200]
**Describe the bug**
When trying to build BTCPay Server on master on Linux, I get the following error:
```
 StoreLightningNetworkPaymentMethodsController.cs(52, 41): [CS0246] The type or namespace name 'LightningNetworkPaymentMethodData' could not be found (are you missing a using directive or an assembly reference?)
```

**To Reproduce the bug**
To reproduce, try building BTCPayServer on your dev environment on master.
**Expected behavior**

**Logs (if applicable)**
```
 StoreLightningNetworkPaymentMethodsController.cs(52, 41): [CS0246] The type or namespace name 'LightningNetworkPaymentMethodData' could not be found (are you missing a using directive or an assembly reference?)
```
 

**Additional context**
I tried to fix it by  `Microsoft.Extensions.Options;` on top of the StoreLightningNetworkPaymentMethodsController.cs per @Kukks suggestion but was unable to fix this issue with this.

**Comment by Kukks** [comment]
I just pushed a fix, can you verify if it works?

**Comment by pavlenex** [comment]
Unfortunately it still doesn't work.

![image](https://user-images.githubusercontent.com/36959754/104810022-41a58200-57f2-11eb-8447-16c8c744dec8.png)

**Comment by pavlenex** [comment]
After a few attempts, on IDE I'm using I did Tools > NuGet >  NuGet Restore fixed it.
