### ISSUE TITLE
[Bug]: ERR_RATE_UNAVAILABLE with Kraken

### ISSUE THREAD

**Issue by d2ro** [btcpayserver/btcpayserver#4027]
### What is your BTCPay version?

I'm running BTCPay 1.6.6.

### How did you deploy BTCPay Server?

https://github.com/btcpayserver/btcpayserver-docker

### What happened?

BTCPay gives an error when trying to get exchange rates from Kraken (see Screenshot):

> BTC_EUR | (ERR_RATE_UNAVAILABLE(kraken, BTC_EUR)) * (0.995, 1.005)
> XMR_EUR | (ERR_RATE_UNAVAILABLE(kraken, XMR_BTC) * ERR_RATE_UNAVAILABLE(kraken, BTC_EUR)) * (0.995, 1.005)

![btcpay](https://user-images.githubusercontent.com/78594032/183618277-dc042439-503b-4e85-b111-c889341600c4.png)

Getting the rates with curl works fine on the server:

```
# curl "https://api.kraken.com/0/public/Ticker?pair=XXBTZEUR,XXMRZEUR"
{"error":[],"result":{"XXBTZEUR":{"a":["23052.70000","4","4.000"],"b":["23052.60000","1","1.000"],"c":["23052.70000","0.00064988"],"v":["313.62198471","1165.18014950"],"p":["23302.98053","23480.07750"],"t":[7742,24326],"l":["23043.70000","23043.70000"],"h":["23461.00000","23759.10000"],"o":"23348.20000"},"XXMRZEUR":{"a":["160.89000000","3","3.000"],"b":["160.80000000","1","1.000"],"c":["160.82000000","0.17668000"],"v":["1963.85005144","3720.94757456"],"p":["165.23690132","164.58711410"],"t":[531,1339],"l":["160.82000000","160.82000000"],"h":["168.48000000","168.48000000"],"o":"164.18000000"}}}
```

### How did you encounter this bug?

Creating an invoice failed after the upgrade.

### Relevant log output

```shell
docker logs --tail 100 generated_btcpayserver_1
[...]
warn: PayServer:      Warning: Error while trying to load rates from cache
System.FormatException: Invalid currency pair
   at BTCPayServer.Rating.CurrencyPair.Parse(String str) in /source/BTCPayServer.Rating/CurrencyPair.cs:line 21
   at BTCPayServer.Services.Rates.BackgroundFetcherRateJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /source/BTCPayServer.Rating/Providers/BackgroundFetcherRateProvider.cs:line 40
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at BTCPayServer.Services.SettingsRepository.Deserialize[T](String value) in /source/BTCPayServer/Services/SettingsRepository.cs:line 72
   at BTCPayServer.Services.SettingsRepository.<>c__DisplayClass4_0`1.<<GetSettingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at BTCPayServer.Services.SettingsRepository.<>c__DisplayClass4_0`1.<<GetSettingAsync>b__0>d.MoveNext() in /source/BTCPayServer/Services/SettingsRepository.cs:line 33
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at BTCPayServer.Services.SettingsRepository.GetSettingAsync[T](String name) in /source/BTCPayServer/Services/SettingsRepository.cs:line 29
   at BTCPayServer.HostedServices.RatesHostedService.TryLoadRateCache() in /source/BTCPayServer/HostedServices/RatesHostedService.cs:line 118
info: PayServer:      Starting payment request expiration watcher
info: Configuration:  Now listening on: http://0.0.0.0:49392
info: PayServer:      23 pending payment requests being checked since last run
info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
warn: PayServer:      Error while contacting exchange kraken: EQuery:Invalid asset pair
warn: PayServer:      Error while contacting exchange kraken: EQuery:Invalid asset pair
warn: PayServer:      Error while contacting exchange kraken: EQuery:Invalid asset pair
[...]
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by d2ro** [comment]
A workaround is enabling advanced rate rule scripting and using a different exchange rate provider, e.g.:

```
BTC_EUR = binance(BTC_EUR);
XMR_EUR = binance(XMR_BTC) * binance(BTC_EUR);
```

**Comment by mhooSec** [comment]
After changing the primary provider from Kraken to Bitfinex using Store Settings -> Rates -> Preferred Price Source, price gets fed correctly, however I can see in the logs that requests are still being sent to Kraken every 30 seconds in the background.

I also tried using @d2ro 's advance rule scripting solution, and while price is also being received, there are still connection attempts to Kraken in the background for some reason, with the same "EQuery:Invalid asset pair" error.

**Comment by novelnet** [comment]
same issues, binance as alternative seems to not support CHF rates tho

**Comment by Kukks** [comment]
fixed in https://github.com/btcpayserver/btcpayserver/commit/15e1169f6211f401e7a53ae4b576243bef565ca7

**Comment by vbrekher** [comment]
same error.  In the setting I've setup Preferred Price Source coingeko however btcpay server keeps contacting contacting other exchanges resulting in 504 gateway time-out on the payment page.
```
2022-08-21 12:38:07.843 +00:00 [WRN] Error while contacting exchange coingecko: A task was canceled.
2022-08-21 12:38:07.845 +00:00 [WRN] Error while contacting exchange kraken: A task was canceled.
2022-08-21 12:38:37.844 +00:00 [WRN] Error while contacting exchange coingecko: A task was canceled.
2022-08-21 12:38:57.847 +00:00 [WRN] Error while contacting exchange kraken: A task was canceled.
2022-08-21 12:39:47.845 +00:00 [WRN] Error while contacting exchange coingecko: A task was canceled.
2022-08-21 12:39:47.845 +00:00 [WRN] Error while contacting exchange kraken: A task was canceled.
2022-08-21 12:39:57.852 +00:00 [WRN] Error while contacting exchange okex: APIRequest timeout
2022-08-21 12:40:37.846 +00:00 [WRN] Error while contacting exchange coingecko: A task was canceled.
2022-08-21 12:40:37.846 +00:00 [WRN] Error while contacting exchange kraken: A task was canceled.
2022-08-21 12:40:47.848 +00:00 [WRN] Error while contacting exchange okex: APIRequest timeout
2022-08-21 12:41:07.845 +00:00 [WRN] Error while contacting exchange coingecko: A task was canceled.
2022-08-21 12:41:07.845 +00:00 [WRN] Error while contacting exchange kraken: A task was canceled.
2022-08-21 12:41:37.844 +00:00 [WRN] Error while contacting exchange okex: APIRequest timeout
```

**Comment by Kukks** [comment]
This was fixed. Update to latest.

**Comment by almostheaven1863** [comment]
I am now getting this error when trying to create a payment request. Even when I change the provider, it still cannot get the rate. I have not changed any settings to make this start failing.

**Comment by Kukks** [comment]
> I am now getting this error when trying to create a payment request. Even when I change the provider, it still cannot get the rate. I have not changed any settings to make this start failing.

What currency is failing and which providers>

**Comment by alexandervlpl** [comment]
This is currently happening with XMR when I try to create an invoice, latest release v1.13.1+ca55e1f30 (Altcoins).

```
05/31/2024 05:38:14:Info Creation of invoice starting
05/31/2024 05:38:14:Info BTC_USD: The rating rule is kraken(BTC_USD)
05/31/2024 05:38:14:Info BTC_USD: The evaluated rating rule is ERR_RATE_UNAVAILABLE(kraken, BTC_USD)
05/31/2024 05:38:14:Error BTC_USD: Rate rule error (RateUnavailable)
05/31/2024 05:38:14:Error BTC_USD: Exception reaching exchange kraken (the bid should be lower than ask (Parameter 'bid'))
05/31/2024 05:38:14:Info XMR_USD: The rating rule is kraken(XMR_BTC) * kraken(BTC_USD)
05/31/2024 05:38:14:Info XMR_USD: The evaluated rating rule is ERR_RATE_UNAVAILABLE(kraken, XMR_BTC) * ERR_RATE_UNAVAILABLE(kraken, BTC_USD)
05/31/2024 05:38:14:Error XMR_USD: Rate rule error (RateUnavailable)
05/31/2024 05:38:14:Error XMR_USD: Exception reaching exchange kraken (the bid should be lower than ask (Parameter 'bid'))
```

**Comment by ether-wan** [comment]
Worki

> This is currently happening with XMR when I try to create an invoice, latest release v1.13.1+ca55e1f30 (Altcoins). Unfortunately, AFAIK Kraken is the only source that worked with XMR so Monero support is now completely broken?
> 
> ```
> 05/31/2024 05:38:14:Info Creation of invoice starting
> 05/31/2024 05:38:14:Info BTC_USD: The rating rule is kraken(BTC_USD)
> 05/31/2024 05:38:14:Info BTC_USD: The evaluated rating rule is ERR_RATE_UNAVAILABLE(kraken, BTC_USD)
> 05/31/2024 05:38:14:Error BTC_USD: Rate rule error (RateUnavailable)
> 05/31/2024 05:38:14:Error BTC_USD: Exception reaching exchange kraken (the bid should be lower than ask (Parameter 'bid'))
> 05/31/2024 05:38:14:Info XMR_USD: The rating rule is kraken(XMR_BTC) * kraken(BTC_USD)
> 05/31/2024 05:38:14:Info XMR_USD: The evaluated rating rule is ERR_RATE_UNAVAILABLE(kraken, XMR_BTC) * ERR_RATE_UNAVAILABLE(kraken, BTC_USD)
> 05/31/2024 05:38:14:Error XMR_USD: Rate rule error (RateUnavailable)
> 05/31/2024 05:38:14:Error XMR_USD: Exception reaching exchange kraken (the bid should be lower than ask (Parameter 'bid'))
> ```
> 
> **Edit: It's not working for BTC as well:** ![image](https://private-user-images.githubusercontent.com/8945883/335471641-d603422e-42ad-4cde-a9f5-13ca257bb634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDU5ODksIm5iZiI6MTcxNzE0NTY4OSwicGF0aCI6Ii84OTQ1ODgzLzMzNTQ3MTY0MS1kNjAzNDIyZS00MmFkLTRjZGUtYTlmNS0xM2NhMjU3YmI2MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDg1NDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQ0ZDExYWNkZjRjNDNlNjQ3ODgyZGQ3ZTk2MWMxODIzYTJhMjE2YjE3ZThlMWIzOWIwNjUzY2I4YzBjOGMzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._yK2jNBjcZxrl7V39fRG0mCbmT2uKwMZuDa74FQtGNg)

Working with Bitfinex price source

**Comment by alexandervlpl** [comment]
Looks like Kraken is hardcoded somewhere in the Monero code:

![image](https://github.com/btcpayserver/btcpayserver/assets/8945883/9168b4ba-b4f7-458f-8580-e9a893fc47dd)
