### ISSUE TITLE
[Bug]: No route hints for private channels for invoices generated from Pay Button

### ISSUE THREAD

**Issue by vindard** [btcpayserver/btcpayserver#4070]
### What is your BTCPay version?

BTCPay Server v1.6.9.0 

---

### How did you deploy BTCPay Server?

Lunanode
[1-click install](https://docs.btcpayserver.org/Deployment/LunaNode/)

---

### What happened?

When I generate invoices using the Pay Button plugin, the invoices do not have route hints.

I've set the option already from the top-level Lightning wallet (I'm using LNBank), and it wokrs fine for my PoS app and from LNBank receives directly. 

---

### How did you encounter this bug?

I generated an invoice from my Pay Button

---

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Is the underlying node LND? I tried to reproduce this and found that there seem to be different results, depending on whether LND or Core Lightning is used: Their defaults seem to vary and our `CreateInvoiceCoreRaw` (which the Pay Button ends up using) doesn't take the setting into consideration.

From first looks it seems like there are more places where this needs fixing (see #4072 and potentially other places as well).

**Comment by vindard** [comment]
> Is the underlying node LND? 

Yes lnd

**Comment by Kukks** [comment]
https://github.com/btcpayserver/BTCPayServer.Lightning/pull/94 should fix this since you are on lnd. 


CLN and eclair won't work just yet though as it requires btcpay.ln changes

**Comment by dennisreimann** [comment]
@kukks Other than #4072, this issue isn't fixed, I still need to investigate.

**Comment by dennisreimann** [comment]
I tried to dig deeper here and from what I see by now we are passing through the necessary parameter, but the route hints do not get included. I can even reproduce this on the CLI, so this isn't specific to our implementation — I assume there is either a bug in LND or some additional logic, that decides which channels get included there.

Reproduction (leaving out the irrelevant parts of the responses):

```bash
BTCPayServer.Tests ➜ ./docker-merchant-lncli.sh listchannels                                                                                                                                                                                                                                                                                                                                                     
{
    "channels": [
        {
            "active": true,
            "remote_pubkey": "023846c9bc0c242646155e768247b0819da295924bee36360ee5c8daae0eaea960",
            "channel_point": "5dd2cef3e5afe8d56ff3224b7dfc726260c294c279a0fa3525c630eae0fb5107:0",
            "chan_id": "1733929837068288",
            "capacity": "5000000",
            "local_balance": "2450000",
            "remote_balance": "2546530",
            "private": true
        }
    ]
}


BTCPayServer.Tests ➜ ./docker-merchant-lncli.sh addinvoice --amt 21 --private                                                                                                                                                                                                                                                                                                                                    
{
    "r_hash": "7388dbb64bf55d7adbb5cd15312d270c42c8b1b8d30f9b0c6c30db87dd37fba5",
    "payment_request": "lnbcrt210n1p3jgmwwpp5wwydhdjt74wh4ka4e52nztf8p3pv3vdc6v8ekrrvxrdc0hfhlwjsdqqcqzpgxqyz5vqsp57jm5j6pps2czu3wh59ujegym6ewnhhwf54z3kxe7janc390hes9s9qyyssqf5g8hdfw5hjjez5dppv7v492y2dlaw4hresecxqcpxpdsrhsyn23ygcgqj2at9gynkvqhse2he4rk5x5usnkfu8r5vtqju05n76st2sqansjgq"
}


BTCPayServer.Tests ➜ ./docker-customer-lncli.sh decodepayreq lnbcrt210n1p3jgmwwpp5wwydhdjt74wh4ka4e52nztf8p3pv3vdc6v8ekrrvxrdc0hfhlwjsdqqcqzpgxqyz5vqsp57jm5j6pps2czu3wh59ujegym6ewnhhwf54z3kxe7janc390hes9s9qyyssqf5g8hdfw5hjjez5dppv7v492y2dlaw4hresecxqcpxpdsrhsyn23ygcgqj2at9gynkvqhse2he4rk5x5usnkfu8r5vtqju05n76st2sqansjgq                                                                                
{
    "destination": "0389dba0af705d0ab6dfbd9cf728391a35a84b38c8f3824875f74ea31333d48acc",
    "payment_hash": "7388dbb64bf55d7adbb5cd15312d270c42c8b1b8d30f9b0c6c30db87dd37fba5",
    "num_satoshis": "21",
    "route_hints": [
    ],
    "payment_addr": "f4b749682182b02e45d7a1792ca09bd65d3bddc9a5451b1b3e97678895f7cc0b",
    "num_msat": "21000"
}
```

**Comment by Collom75** [comment]
Good morning how do you withdraw your account?

**Comment by pavlenex** [comment]
@dennisreimann were you able to locate an underlying problem for this one?

**Comment by dennisreimann** [comment]
The PayButton still uses an old (BitPay-compatible) API to generate the invoices and it's not possible to specify the private route hints parameter with that.

**Comment by pavlenex** [comment]
So I don't think there's anything we can do to solve it besides refactorign the paybutton for greenfield, in which case it's a big breaking change? Should we refactor the pay button to use greenfield?

**Comment by bolatovumar** [comment]
@dennisreimann are you sure it's because of the old API? As far as I can tell the code for the Pay Button ends up using the same method for specifying whether there should be private hints or not and it depends on the setting set on the store.

**Comment by dennisreimann** [comment]
@bolatovumar I just checked, you are correct! It might be a matter of the implementation having custom rules for really including those hints as described [here](https://github.com/btcpayserver/btcpayserver/issues/4070#issuecomment-1250062268). Also checked once more: We are passing on the route hints parameter for LND and CLN correctly.

**Comment by pavlenex** [comment]
@dennisreimann @bolatovumar so what do we do with this opened issue, is there something we can do to improve this or is it implementation related and we cannot address it?

**Comment by dennisreimann** [comment]
I don't see a way to fix it on our end — we seem to be passing through everything correctly.

**Comment by vindard** [comment]
> I don't see a way to fix it on our end — we seem to be passing through everything correctly.

This is still an issue, but it's an lnd thing I think. I posted an issue with some details across on their server https://github.com/lightningnetwork/lnd/issues/7753
