### ISSUE TITLE
[Bug]: Das does not sync anymore, hangs at 99%

### ISSUE THREAD

**Issue by vsatmydynipnet** [btcpayserver/btcpayserver#4206]
### What is your BTCPay version?

© BTCPay Server v1.6.12.0 (Altcoins) 

### How did you deploy BTCPay Server?

Docker

### What happened?

All worked since a longer time, BTC still is fine, Dash stopped finishing sync:

Your nodes are synching...

Your node is synching the entire blockchain and validating the consensus rules...
DASH

    NBXplorer headers height: 1738697
    Node headers height: 1738697
    Validated blocks: 1738697

99%
BTC

    NBXplorer headers height: 758158
    The node is synchronized (Height: 758158)

### How did you encounter this bug?

see above

### Relevant log output

```shell
022-10-11 07:28:53.257 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2022-10-11 07:28:53.259 +00:00 [INF] TorServices successfully exited...
2022-10-11 07:28:53.264 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2022-10-11 07:28:53.430 +00:00 [INF] PullPaymentHostedService successfully exited...
2022-10-11 07:28:53.504 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2022-10-11 07:28:53.539 +00:00 [INF] NBXplorerListener successfully exited...
2022-10-11 07:28:53.545 +00:00 [INF] LightningListener successfully exited...
2022-10-11 07:28:53.560 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2022-10-11 07:28:53.578 +00:00 [INF] Stop watching invoices
2022-10-11 07:28:54.918 +00:00 [INF] RatesHostedService successfully exited...
2022-10-11 07:28:54.941 +00:00 [INF] DynamicDnsHostedService successfully exited...
2022-10-11 07:28:54.947 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2022-10-11 07:28:54.947 +00:00 [INF] DbMigrationsHostedService successfully exited...
2022-10-11 07:33:08.638 +00:00 [INF] Root Path: /
2022-10-11 07:33:13.389 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2022-10-11 07:33:13.812 +00:00 [INF] Starting listening NBXplorer (BTC)
2022-10-11 07:33:13.957 +00:00 [INF] Starting listening NBXplorer (DASH)
2022-10-11 07:33:14.024 +00:00 [INF] Start watching invoices
2022-10-11 07:33:14.210 +00:00 [INF] Starting payment request expiration watcher
2022-10-11 07:33:14.599 +00:00 [INF] 0 pending payment requests being checked since last run
2022-10-11 07:33:56.522 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2022-10-11 07:33:57.612 +00:00 [INF] BTC: 0 payments happened while offline
2022-10-11 07:33:57.612 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2022-10-11 07:37:23.324 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2022-10-11 07:37:23.326 +00:00 [INF] TorServices successfully exited...
2022-10-11 07:37:23.330 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2022-10-11 07:37:23.357 +00:00 [INF] PullPaymentHostedService successfully exited...
2022-10-11 07:37:23.370 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2022-10-11 07:37:23.372 +00:00 [INF] NBXplorerListener successfully exited...
2022-10-11 07:37:23.382 +00:00 [INF] LightningListener successfully exited...
2022-10-11 07:37:23.385 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2022-10-11 07:37:23.396 +00:00 [INF] Stop watching invoices
2022-10-11 07:37:23.793 +00:00 [INF] RatesHostedService successfully exited...
2022-10-11 07:37:23.800 +00:00 [INF] DynamicDnsHostedService successfully exited...
2022-10-11 07:37:23.804 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2022-10-11 07:37:23.804 +00:00 [INF] DbMigrationsHostedService successfully exited...
2022-10-11 07:39:24.547 +00:00 [INF] Root Path: /
2022-10-11 07:39:25.629 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2022-10-11 07:39:25.884 +00:00 [INF] Starting listening NBXplorer (BTC)
2022-10-11 07:39:25.984 +00:00 [INF] Starting listening NBXplorer (DASH)
2022-10-11 07:39:26.005 +00:00 [INF] Start watching invoices
2022-10-11 07:39:26.113 +00:00 [INF] Starting payment request expiration watcher
2022-10-11 07:39:26.279 +00:00 [INF] 0 pending payment requests being checked since last run
2022-10-11 07:39:46.713 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2022-10-11 07:39:46.718 +00:00 [INF] TorServices successfully exited...
2022-10-11 07:39:46.730 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2022-10-11 07:39:46.767 +00:00 [INF] PullPaymentHostedService successfully exited...
2022-10-11 07:39:46.991 +00:00 [ERR] BTC: NBXplorer error `Connection refused (nbxplorer:32838)`
2022-10-11 07:39:46.991 +00:00 [ERR] DASH: NBXplorer error `Connection refused (nbxplorer:32838)`
2022-10-11 07:39:46.999 +00:00 [ERR] BTC: NBXplorer error `Connection refused (nbxplorer:32838)`
2022-10-11 07:39:47.000 +00:00 [ERR] DASH: NBXplorer error `Connection refused (nbxplorer:32838)`
2022-10-11 07:39:51.636 +00:00 [INF] NBXplorerListener successfully exited...
2022-10-11 07:39:51.652 +00:00 [INF] LightningListener successfully exited...
2022-10-11 07:39:51.655 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2022-10-11 07:39:51.679 +00:00 [INF] Stop watching invoices
2022-10-11 07:39:52.287 +00:00 [INF] RatesHostedService successfully exited...
2022-10-11 07:39:52.304 +00:00 [INF] DynamicDnsHostedService successfully exited...
2022-10-11 07:39:52.311 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2022-10-11 07:39:52.312 +00:00 [INF] DbMigrationsHostedService successfully exited...
2022-10-11 07:43:54.029 +00:00 [INF] Root Path: /
2022-10-11 07:43:56.967 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2022-10-11 07:43:57.510 +00:00 [INF] Starting listening NBXplorer (BTC)
2022-10-11 07:43:57.631 +00:00 [INF] Starting listening NBXplorer (DASH)
2022-10-11 07:43:57.647 +00:00 [INF] Start watching invoices
2022-10-11 07:43:57.706 +00:00 [INF] Starting payment request expiration watcher
2022-10-11 07:43:57.841 +00:00 [INF] 0 pending payment requests being checked since last run
2022-10-11 07:48:49.964 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2022-10-11 07:48:50.186 +00:00 [INF] BTC: 0 payments happened while offline
2022-10-11 07:48:50.187 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2022-10-11 08:11:12.158 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2022-10-11 08:11:12.165 +00:00 [INF] TorServices successfully exited...
2022-10-11 08:11:12.172 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2022-10-11 08:11:12.255 +00:00 [INF] PullPaymentHostedService successfully exited...
2022-10-11 08:11:12.326 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2022-10-11 08:11:12.347 +00:00 [INF] NBXplorerListener successfully exited...
2022-10-11 08:11:12.357 +00:00 [INF] LightningListener successfully exited...
2022-10-11 08:11:12.359 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2022-10-11 08:11:12.379 +00:00 [INF] Stop watching invoices
2022-10-11 08:11:14.087 +00:00 [INF] DynamicDnsHostedService successfully exited...
2022-10-11 08:11:14.090 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2022-10-11 08:11:14.090 +00:00 [INF] DbMigrationsHostedService successfully exited...
2022-10-11 08:11:34.554 +00:00 [INF] Root Path: /
2022-10-11 08:11:37.217 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2022-10-11 08:11:37.553 +00:00 [INF] Starting listening NBXplorer (BTC)
2022-10-11 08:11:37.640 +00:00 [INF] Starting listening NBXplorer (DASH)
2022-10-11 08:11:37.656 +00:00 [INF] Start watching invoices
2022-10-11 08:11:37.717 +00:00 [INF] Starting payment request expiration watcher
2022-10-11 08:11:37.987 +00:00 [INF] 0 pending payment requests being checked since last run
2022-10-11 08:12:29.046 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2022-10-11 08:12:29.232 +00:00 [INF] BTC: 0 payments happened while offline
2022-10-11 08:12:29.232 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)

© BTCPay Server v1.6.12.0 (Altcoins)
```

### What browser do you use?

Firefox

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by valsha** [comment]
yes, I have the same problem with Dash
![image](https://user-images.githubusercontent.com/7966513/195112272-a4eecb4b-f63f-42d0-9d86-0e98ba4505cc.png)

**Comment by vsatmydynipnet** [comment]
I updated a few Minutes ago and there was some nbexplorer parts updated, but it still shows:

© BTCPay Server v1.6.12.0 (Altcoins) 

BTC

    NBXplorer headers height: 758307
    The node is synchronized (Height: 758307)

DASH

    NBXplorer headers height: 1738697
    Node headers height: 1738697
    Validated blocks: 1738697

99%

**Comment by valsha** [comment]
@Kukks please update Dash to 18.0.2 https://github.com/dashpay/dash/releases

**Comment by valsha** [comment]
this problem was also in the Dash Core.
when i updated Dash Core to 18.0.2, all was good now.
https://github.com/dashpay/dash/releases
`When upgrading from a version < 18.0, a migration process will occur.`

**Comment by Kukks** [comment]
> @Kukks please update Dash to 18.0.2 [dashpay/dash/releases](https://github.com/dashpay/dash/releases)

Please submit a PR with a new dash docker image build to dockerfile-deps if you wish this update.

**Comment by valsha** [comment]
> > @Kukks please update Dash to 18.0.2 [dashpay/dash/releases](https://github.com/dashpay/dash/releases)
> 
> Please submit a PR with a new dash docker image build to dockerfile-deps if you wish this update.

I think you don't use any files from Dash Core :) sorry
Maybe the problem in NBitcoin or https://github.com/btcpayserver/btcpayserver/tree/master/BTCPayServer.Common/Altcoins/Monero ?

**Comment by vsatmydynipnet** [comment]
I updated today because I saw nbexplorer stuff is included, but still have:

Your nodes are synching...

Your node is synching the entire blockchain and validating the consensus rules...
DASH

    NBXplorer headers height: 1738697
    Node headers height: 1738697
    Validated blocks: 1738697

98%


BTC

    NBXplorer headers height: 759492
    The node is synchronized (Height: 759492)

[Watch this video](https://www.youtube.com/watch?v=OrYDehC-8TU) to understand the importance of blockchain synchronization.

**Comment by valsha** [comment]
@NicolasDorier sorry, maybe you can check this problem? Thank you.

**Comment by NicolasDorier** [comment]
Please ask someone to bump dash to 0.18.2 on https://github.com/btcpayserver/dockerfile-deps , we aren't maintaining it for them.

**Comment by valsha** [comment]
@Kukks can you please check PR https://github.com/btcpayserver/dockerfile-deps/pull/58
Thank you.

**Comment by valsha** [comment]
The problem is solved.
1. Deleted all files in /var/lib/docker/volumes/generated_dash_datadir/_data
2. Restart btcpay server
3. Resync Dash blocks

**Comment by vsatmydynipnet** [comment]
Updated and resyncing, but 1763807 still does not look good. lets see what happens if sync is at this block.

 Your node is synching the entire blockchain and validating the consensus rules...
DASH

    NBXplorer headers height: 1763807
    Node headers height: 1763807
    Validated blocks: 219379

1%

**Comment by vsatmydynipnet** [comment]
It is synced again! THANK YOU very much!
