### ISSUE TITLE
[Bug]: Point of Sale double quoting of "&" in Item Title

### ISSUE THREAD

**Issue by prusnak** [btcpayserver/btcpayserver#4794]
### What is your BTCPay version?

v1.7.7

### How did you deploy BTCPay Server?

manually

### What happened?

- I added an item named "M&S instantni polivka" to Point of Sale

### How did you encounter this bug?

- I went to the PoS and observe this:

<img width="314" alt="Screenshot 2023-03-21 at 12 33 43" src="https://user-images.githubusercontent.com/42201/226594719-22b5b3c8-fefb-473e-b992-949a06d4e414.png">

### What browser do you use?

Safari on macOS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Hey. This was fixed, can you update and give it a try?

**Comment by dennisreimann** [comment]
@pavlenex No, this wasn't fixed ­— I think it got introduced with the recent CSP fixes. Fix in #4798.

**Comment by prusnak** [comment]
Please reopen - this issue has been reintroduced in PoS redesign deployed in 1.11.0

**Comment by dennisreimann** [comment]
@prusnak Fixed and added to a PR I'll publish once #5238 is merged. Will be part of the next bugfix release. Thanks for reporting!

**Comment by dennisreimann** [comment]
Fixes with #5241.
