### ISSUE TITLE
[Bug]: UI clarify information about restoring LND backup.

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#5612]
### What is your BTCPay version?

BTCPay v1.12.3

### How did you deploy BTCPay Server?

docker

### What happened?

The text around the link to LND revovery procedure is unclear. It should mention that the recovery won't work with LND in BTCPay as the `lncli create` command won't work as it only works on first startup and is done automatically on BTCPay deployment.

![image](https://github.com/btcpayserver/btcpayserver/assets/1136761/7490f661-6b41-4c61-b27c-051fbb21781b)

Maybe link to docs and there explain it better and also mention blixt as a way to close channels and recover funds as SCB won't allow restore the channels but only to close them anyway. 

### How did you encounter this bug?

(not tested myself due the lack of LND enabled on BTCPay) should be on the LND backup page in the BTCPay UI

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by martiankoder** [comment]
Yes, this is exactly what is happening to me. I still can't restore my fund (Lightining LND). I wrote down the 24 words and downloaded the .bak file (from the UI). I spinned up another lunnanode. SSH into it. And start to restore like instructed in this document:
https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md
sudo su -
cd btcpayserver-docker
./bitcoin-lncli.sh create
The command (./bitcoin-lncli.sh create) gives me an error: "Input wallet password: [lncli] inappropriate ioctl for device"
I stuck at this error for days.
If btcpay server can't help restore with this method, it should say so in clarity on the website, and show how to restore fund with alternative method. 
In this post with simillar error (https://github.com/btcpayserver/btcpayserver/issues/2853), Kukks said "This is not a supported feature by our deployment. Why do you want to do this? Is it a disaster recovery scenario?" , but did not offer the solution.
So now what is the solution? How do you recover funds (on chain and offchain (probably will close channels so funds settle onchain) .
I tried to import to Bilxt wallet and (24 words and .bak file) but can't see my off chain funds (did not see if channels being closed or in process), there is no logs or anything?
Can we really restore fund with BCTpay server? Thank you

**Comment by dennisreimann** [comment]
What are the possibilities here? I tried stopping the server, deleting the old wallet and its loickfile and afterwards running the `create` command to recover the previous wallet, but the container crashes immediately before I can even recover. I think that's due to the wallet being removed or something else missing.

```
error loading chain control: unable to create wallet controller: invalid passphrase for master public key
LND_CHAIN=btc
LND_ENVIRONMENT=regtest
Added bitcoin.active and bitcoin.regtest to config file /data/lnd.conf
[lnd_unlock_entrypoint] WARNING: UNLOCK FILE DOESN'T EXIST! MIGRATE LEGACY INSTALLATION TO NEW VERSION ASAP
```

I think it would be desirable to support recovering within BTCPay Server, especially if the wallet has been set up that way.

/cc @rockstardev

**Comment by pavlenex** [comment]
Was this addressed in https://github.com/btcpayserver/btcpayserver-docker/pull/876  or its successor? @ndeet @rockstardev ? 

To me it sounds like we did resolve it, but want to make sure.

```
This version also includes the ability to skip our auto initialization/unlocking of the LND wallet using LND_SKIP_INITUNLOCK environment variable. Once merged this will resolve the issue: https://github.com/btcpayserver/btcpayserver/issues/5612
```

**Comment by ndeet** [comment]
@pavlenex afaics in current master as of today the text on LND Seed Backup is still the same. The link is to the official [recovery instructions](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md). Not sure if what was discussed so that one can make LND not create a wallet and allow for recovery was already implemented @rockstardev. We might also need to update docs to describe how users can recover.

**Comment by warioishere** [comment]
Because lnd needs to be locked to change for an exisiting the azeed.  You cannot change the azeed after the stack is running and wallet.db beeing loaded so you would need to try as following:

Both options do require that the whole btcpay stack is fire up already once and a fresh wallet.db is already created. 

**Option1:**

So you would need to do as follows: Create a script that stops the lnd container, and restarts it without using the docker-initunlock.sh script. 

start the

`docker exec -it btcpayserver_lnd_bitcoin lncli --macaroonpath /root/.lnd/admin.macaroon create`

command. Follow the shell to restore from an exisiting wallet. Give time, because lnd goes into recovery mode. It can take quiet a while untils its done. Sometimes can take hours to scan for existing funds. The script should watch out for lnd to be started up properly again and that its not in current recoverymode. 

Initialize the next startup of lnd after recovery mode again with the docker-initunlock script. Things should be set. 

**Option2 with fragments as you wanted to do**

you unlock lnd as it should be unlocked in the official way with the options

```
wallet-unlock-password-file=/data/lnd/password.txt
wallet-unlock-allow-create=true
```

in the lnd.conf

then you would need to remove the complete unlocking method from the initunlock script. 

Then you could use the fragment method and use a special lnd restore fragment that comments out just those two options in lnd.confand start lnd without those two options.

then you would need to setup an exisiting seed again with 

`docker exec -it btcpayserver_lnd_bitcoin lncli --macaroonpath /root/.lnd/admin.macaroon create`

then you would follow official unlock methods of lnd which would make it more compatible with official development.

Would you let me know where the correct docker-unlock.script is again? I find two files in:

```
/var/lib/docker/overlay2/44e789184998d63344702e2c1bad030388d2ae72fc99e5f2b7ca25887d7ed9cc/merged/docker-initunlocklnd.sh
/var/lib/docker/overlay2/da1329bfb3d97dc8cb640925426775030eaf831e36b48d4357dd2fd0f53cdd2c/diff/docker-initunlocklnd.sh
root@btcpay-test:~/btcpayserver-docker# 
```

didnt had time to test further now, but will do later

**Comment by ziggie1984** [comment]
When creating a new instance with the same seed, it is very important to not reuse any former data from the previous setup (channel.db) for example. The recovery must be done on a clean setup in terms of the LND data.

**Comment by warioishere** [comment]
@ziggie1984 @rockstardev @ndeet 

I think the question was just how to restore an azeed, not a whole system with channels?

if you wanna restore a whole lnd stack with channel, then go with a script that takes a backup of the whole lnd directory. and the recover script needs to wipe the whole lnd directory first before it replaces the back which has been done. 

About what ziggie said, maybe the container should be started completly freshly without a wallet being setup first, so without the `docker-initunlock.sh` script  lnd then creates a temporay tls.cert file which can be used to restore from an exisiting azeed. No files are being made when one first startup withough an exisiting wallet.

you should then use:

docker exec -it btcpayserver_lnd_bitcoin lncli --tlscertpath /root/.lnd/tls.cert.tmp create

then after that the user can restore with an exisiting azeed and start up with a clean lnd folder without the data from the first firing up like in my first brainstorming comment.

I think everything could also be done with calling the rest api of lnd to integrate it in the GUI as a user recommended. You could also integrate the backup and restore of the lnd node into the Web Gui of btcpay server

**Comment by warioishere** [comment]
I wrote an update on my backup and restore articles for multiple systems also covering btcpay docker.
Its in germany, but a translator should help. This is the current method on how to restore a previous lnd azeed on a new btcpay docker setup:

https://yourdevice.ch/der-backup-restore-leitfaden-fuer-lighning-fullnodes/#LND_Wallet_von_BTCPay_Docker_wiederherstellen
