### ISSUE TITLE
CssThemeManager not honoring --rootpath option

### ISSUE THREAD

**Issue by enorrmann** [btcpayserver/btcpayserver#659]
instead, _bootstrapUri and _creativeStartUri are always pointing to
/vendor/

should be
rootpath/vendor/

**Comment by enorrmann** [comment]
same happens with absolute URL /payment-requests
should be 
rootpath/payment-requests/hub

**Comment by ser** [comment]
It exactly what I wanted to report, the bug is in lines:

https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/HostedServices/CssThemeManager.cs#L24

and

https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/HostedServices/CssThemeManager.cs#L30

**Comment by ser** [comment]
@Kukks and yours listener.js also hard codes the URI :(

**Comment by Kukks** [comment]
@ser it does not `var connection = new signalR.HubConnectionBuilder().withUrl("/apps/hub").build();`

**Comment by ser** [comment]
True, sorry for false alarm - but my first comment is still valid, related to CssThemeManager.cs

**Comment by NicolasDorier** [comment]
You are correct, fixing it.

**Comment by NicolasDorier** [comment]
@ser actually just tested it, it should work what page is problematic?

**Comment by NicolasDorier** [comment]
@Kukks all the SignalR hubs are broken with a root path

**Comment by NicolasDorier** [comment]
For theme, as long as they are referenced like this https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Shared/_Layout.cshtml#L22 it should work.

**Comment by ser** [comment]
all pages have broken link to default themes, it is always / regardless of set rootpath

installation with rootpath gives no bootstrap loaded so it looks pretty strange :) it can be fixed by specifying an external theme of course, but by default it is not easy to navigate :) :)

**Comment by NicolasDorier** [comment]
Well this is strange, I do not manage to reproduce. Who did you do?

**Comment by NicolasDorier** [comment]
Ah shit, managed to reproduce on the docker dpeloy. Checking it

**Comment by NicolasDorier** [comment]
Linux only issue... Fixed by https://github.com/btcpayserver/btcpayserver/commit/7e67ca1413756574832d96f127c14c4f8cb63fc9

**Comment by NicolasDorier** [comment]
Because on linux `/` is absolutely and absolute path...

**Comment by NicolasDorier** [comment]
Reopening until the SignalR hubs are not fixed (ping @Kukks )

**Comment by enorrmann** [comment]
I found more absolute links on the invoice checkout page

http://myserver.com/imlegacy/bitcoin.svg
http://myserver.com/locales/en.json

should be 
http://myserver.com/btcpayserver/imlegacy/bitcoin.svg
http://myserver.com/btcpayserver/locales/en.json

**Comment by NicolasDorier** [comment]
I think my fix about should fix all

**Comment by enorrmann** [comment]
> I think my fix about should fix all

nope, I'm testing it right now with latest from master branch :(

**Comment by NicolasDorier** [comment]
One more fix, anything else?

**Comment by NicolasDorier** [comment]
`btcpay.js` does not show the popup with RootPath. I have no idea why though. No error, and things seems to be set correctly.

**Comment by NicolasDorier** [comment]
@enorrmann let me know if, aside from SignalR hub, you find any stuff broken.
Also, if you have any idea about what is wrong with the iframe...

**Comment by NicolasDorier** [comment]
I fixed the SignalR hub @Kukks  https://github.com/btcpayserver/btcpayserver/commit/75974037bc4a815d104a866a90423990ec8c13d8

**Comment by NicolasDorier** [comment]
anything missing?

**Comment by NicolasDorier** [comment]
Ok the popup issue should be gone https://github.com/btcpayserver/btcpayserver/commit/2138b7dcb801fd7767eb6f128291486697a315fe @rockstardev

**Comment by NicolasDorier** [comment]
I think I fixed everything, @enorrmann please reopen another issue or reopen another if you find another problem. Will probably make a release tomorrow.

**Comment by enorrmann** [comment]
thanks a lot, will continue testing asap

**Comment by enorrmann** [comment]
> I think I fixed everything, @enorrmann please reopen another issue or reopen another if you find another problem. Will probably make a release tomorrow.

still getting some 404 in a test payment request
http://rayo.tech/btcpayserver/payment-requests/53486c9e-5710-4285-bd40-d989b57f75dc

lots of errors in browsers js console..

**Comment by NicolasDorier** [comment]
Did you pulled latest? Because I can see your backend does not seem to send updated json object.

**Comment by enorrmann** [comment]
yes, actually I deleted and cloned again from scratch..
also, on the server side I'm getting
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext: Failed connection handshake.
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext: Failed connection handshake.

**Comment by NicolasDorier** [comment]
shit, indeed... trying to find the issue.

**Comment by NicolasDorier** [comment]
Ok so one of the problem is that you need to fix your reverse proxy configuration to accept websocket.

Do this https://docs.btcpayserver.org/faq-and-common-issues/faq-wallet#why-is-my-ledger-not-detected-by-btcpay-server

That said, signalr should fallback to SSE and does not so I need to look into it.

**Comment by NicolasDorier** [comment]
The SSE error can be solved with 

`proxy_set_header Connection $http_connection;` so I recommend to add this as well. (You still need websocket though)

**Comment by enorrmann** [comment]
almost there ! 
I updated /etc/nginx/conf.d/default.conf to 

map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}

proxy_set_header Upgrade $http_upgrade;

proxy_set_header Connection $proxy_connection;


and now the payment-requests page is working fine ! 
but! when I press the "pay now" button
another absolure url is crafted
http://rayo.tech/invoice?id=ExQtscjsHwuQW2toPUo1CW&view=modal
should be
http://rayo.tech/btcpayserver/invoice?id=ExQtscjsHwuQW2toPUo1CW&view=modal

**Comment by NicolasDorier** [comment]
Strange... taking a look.

**Comment by NicolasDorier** [comment]
@enorrmann ok now fix should be complete!

**Comment by enorrmann** [comment]
can confirm ... it's working perfectly now
