### ISSUE TITLE
Can't switch from LND -> CLightning 

### ISSUE THREAD

**Issue by thedon-chris** [btcpayserver/btcpayserver#695]
**Describe the problem/bug**
I've switched my BTCPay (docker-setup and aws) from LND->CLightning and BTCPay won't recognize switch and is stuck in LND.
**Your environment**
btcpayserver/btcpayserver:1.0.3.79

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**
This is the 3rd time changing Lightning implementation.
Here's how I've setup
LND->CLightning->LND->CLightning (bug occurs)

**Expected behavior**
BTCPay server settings should switch to show clightning services.
**Actual behavior**
BTCPay server settings showing lnd services.
![Screen Shot 2019-03-19 at 12 24 14 PM](https://user-images.githubusercontent.com/30728737/54623499-fed1c200-4a41-11e9-86b1-0ca3a5938382.png)

**Comment by pavlenex** [comment]
Can you update your btcpay for starters 1.0.3.79 is a tiny bit old, v1.0.3.86 is the latest and there have been some troubles with QR codes display exactly fixed in .80 that may have influenced this.

**Comment by thedon-chris** [comment]
I've updated BTCPay to v1.0.3.86, and still won't change to clightning although docker containers show as clightning is running.

<img width="1515" alt="Screen Shot 2019-03-19 at 12 33 04 PM" src="https://user-images.githubusercontent.com/30728737/54624200-4ad13680-4a43-11e9-9749-541fbfddfeba.png">

**Comment by pavlenex** [comment]
ping @NicolasDorier TLDR, changed from LND->CLightning->LND->CLightning when on 1.0.3.79, now docker shows c-lightning running but Services show LND, weird. Not sure what may cause this.

**Comment by thedon-chris** [comment]
I forgot to mention that I'm simultaneously running 2 BTCPay's on separate servers on aws/docker (1 mainnet and 1 testnet). The testnet was able to make the switch, under the same conditions, mainnet was not.
<img width="1679" alt="Screen Shot 2019-03-19 at 12 58 54 PM" src="https://user-images.githubusercontent.com/30728737/54626142-fdef5f00-4a46-11e9-9fb9-002ff60081ad.png">

**Comment by NicolasDorier** [comment]
@thedon-chris I think you are confusing the servers. The terminal of mainnet is running `lightning`, while the website show `lnd`. This is not possible. Are you sure you are not modifying the wrong server?

Have you checked on the footer of the page of mainnet that the version is .86?

**Comment by thedon-chris** [comment]
Wow how embarrassing. 

I have confused the servers...

Turns out I am managing more than 2 BTCPay's for different cases/projects.

Is there any way we can add the IP address to the BTCPay admin to assist in debugging?

**Comment by thedon-chris** [comment]
Since this is no longer a bug and now a feature request I will close the issue.
